### ISSUE TITLE
3 Frontend screens

### ISSUE THREAD

**Issue by ProRichyMan** [jar04/flask_portfolio#20]
- [x] Must be functionality towards project
- [x] Show bootstrap layouts

**Comment by ProRichyMan** [comment]
<img width="1440" alt="Screen Shot 2021-12-16 at 12 30 36 PM" src="https://user-images.githubusercontent.com/89236893/146444749-97a5afff-4fb4-4fdd-9820-b4ecbf7adc42.png">
<img width="1358" alt="Screen Shot 2021-12-16 at 12 30 03 PM" src="https://user-images.githubusercontent.com/89236893/146444764-4e5883e3-fa60-4f02-9e1d-d87f8e13971f.png">
<img width="1297" alt="Screen Shot 2021-12-16 at 12 30 11 PM" src="https://user-images.githubusercontent.com/89236893/146444772-822cf0ec-c83c-4d59-99bc-ec1ba2be4553.png">

**Comment by Danny4w** [comment]
![image](https://user-images.githubusercontent.com/89228041/146446007-d527a48f-e30b-499c-a286-856653c57f82.png)
