### ISSUE TITLE
Review Ticket Week 3

### ISSUE THREAD

**Issue by ProRichyMan** [jar04/flask_portfolio#25]
Daniel Bertino Commits| [Commits](https://github.com/jar04/flask_portfolio/commits?author=Danny4w)|
Jacob Rozenkrants Commits| [Commits](https://github.com/jar04/flask_portfolio/commits?author=jar04)|
James Lee Commits | [Commits](https://github.com/jar04/flask_portfolio/commits?author=JL1080)|
Reem Ben Ishai Commits| [Commits](https://github.com/jar04/flask_portfolio/commits?author=Reem57)|
Nathan Manangan | [Commits](https://github.com/jar04/flask_portfolio/commits?author=ProRichyMan)|

5.5/6 on Team
Individual scores:
Nathan - 2/2 AP Score : 63/67
Reem - 2/2 AP Score : 62/67
Jacob - 2/2 AP Score: 66/67
James - 2/2 AP Score : 64/67
Daniel - 2/2 AP Score: 58/67

Comments Below V V

**Comment by ProRichyMan** [comment]
Team Section.
Scrum Master and Technical Officer
PBL Highlights.  <readme time box link>
Video <link to one minute video>
Design Manager tangibles
Layout. <source link>
Front End Feature Screen <source link> <runtime link>
Front End Screen 2: <runtime link>
Front End Screen 3: <runtime link>
Scrum Master tangibles
GitHub Scrum Board <tickets in review link> <in progress link>
Scrum Board <post winter break backlog link>
Technical officer tangibles
Database with CRUD:
Runtim <link to CRUD page runtime>
View <link to code supporting crud routes and logic>
Model <link to class and crud>
Deployment manager tangibles
Update procedure: <link to deployment guid that contains procedure for someone to make an update to deployment>
Nginx config: <link to deployment guide containing paste of configuration file>
Service config: <link to deployment guide containing paste of service file>
GitHub admin tangibles
Commit, pull request procedure <link to deployment guide that shows process>
Branching procedure <link to deployment guide that show process to create and merge a branch>
Individual Section.
AP MCQ Test and Corrections <link to results>

**Comment by ProRichyMan** [comment]
Nathan Individual Section.
AP MCQ Test and Corrections <link to results>

**Comment by ProRichyMan** [comment]
Daniel Individual Section.
AP MCQ Test and Corrections <link to results>

**Comment by ProRichyMan** [comment]
James Individual Section.
AP MCQ Test and Corrections <link to results>

**Comment by ProRichyMan** [comment]
Jacob Individual Section.
AP MCQ Test and Corrections <link to results>

**Comment by ProRichyMan** [comment]
Reem Individual Section.
AP MCQ Test and Corrections <link to results>

**Comment by suneelanaidu** [comment]
Link to 1 min video doesn't work. I do not see Database Crud/search on the deployed website. 7.25/8
