### ISSUE TITLE
Week 11 Review Ticket (2)

### ISSUE THREAD

**Issue by ProRichyMan** [jar04/flask_portfolio#44]
4.5/5 Group

PBL theme consistent through project and described in Github Pages 1/1
Sassy / Bootstrap 1/1
Blueprint illustration/demonstration 1/1
CRUD Async Operation - runtime and understanding of JavaScript and Fetch 0.5/1
Individual PBL MVC feature/commits showing algorithms written in JS/Python 1/1

**Comment by nicm2** [comment]
Individual/Pair Evaluation on Create Task Project - 5pts

 Wiki/Jekyll page with design ideas and usage (1/1)
 Create Performance Task PBL feature (1/1)
 Final committed program code showing algorithms written in JS/Python (1/1)
 Written responses to all the prompts in the performance task (.75/1) 
 1min video that meets CB create task requirements (.5/1) 

Team Final Grading Considerations - 5 pts

PBL Github pages. Jekyll, WIKI, live review focus (.5/.5)
 PBL theme consistent through project and described in Github Pages (.5/.5)
 Sassy / Bootstrap (.5/.5)
 Blueprint illustration/demonstration (.25/.5) Blueprint not used to the fullest extent
 CRUD Async Operation - runtime and understanding of JavaScript and Fetch (.5/.5)
 Individual PBL MVC feature/commits showing algorithms written in JS/Python (.5/.5)

Runtime Features shown in 1 min video

 Highlight of best features (.5/.5)
 CRUD/Search on project database tables, easy to identify from UI (.5/.5)
 MVC - a code overview showing usage of MVC (HTML, Routes/Render Template functions, Model functions) (.5/.5)
 Google Search or Google translate implemented (.5/.5)
 Scrum Board - Overview of completed tasks and Github tangibles (.5/.5)
