### ISSUE TITLE
Create a Journal

### ISSUE THREAD

**Issue by ProRichyMan** [jar04/flask_portfolio#6]
- [x] Create a main journal
- [x] Include separate/individual journals for each person

**Comment by Reem57** [comment]
https://docs.google.com/document/d/1vv4x5c7fiFXpvSxoyTqEkVWDi05tGcZZoSaMvb4LJM4/edit

**Comment by Reem57** [comment]
our group's journal
https://docs.google.com/document/d/12rQvrhtsNnlDFDhkCI9sT8w7fTD3y-4FW6W8LPLuf9w/edit?usp=sharing

**Comment by Reem57** [comment]
other group's journal
https://docs.google.com/document/d/1iWY0JFOhnv8dLGOX7WXPdvvbnUYI_WglTmJvhG3r4QQ/edit?usp=sharing
